### ISSUE TITLE
Adjust navigation bar on mobile devices

### ISSUE THREAD

**Issue by Idadelveloper** [unicef/inventory-hugo-theme#36]
# Summary

The navigation bar looks alright on desktop or larger screens. However, the text in it looks disorganized on mobile devices.

## What you expected to happen

All items in the navbar should be aligned to the center and equally spaced.

## What actually happened
Currently, the link to UNICEF global is left-aligned.

**Screenshots**:

![unicefbannerissue](https://user-images.githubusercontent.com/56026636/144088765-6eb0c377-cba5-4852-a764-5c3edeb8bc06.png)

# Other details

Changes should be done in the theme repo: https://github.com/unicef/inventory-hugo-theme

**Comment by jwflory** [comment]
Moved from `unicef/inventory#99`. Also added to the project board for the current sprint ending next Friday (10 December).

+1! I am also wondering if it makes sense to remove the hyperlink from the logo, since the "`Visit UNICEF Global` is already there. Lately I have found myself accidentally clicking the logo to go back to the main page, but instead going to the UNICEF homepage.

**Comment by Idadelveloper** [comment]
@jwflory should I reopen this issue? The navbar is messed up again for mobile devices.
![bad-nav](https://user-images.githubusercontent.com/56026636/148071992-ad001989-2d50-4308-ad65-a1cf0c534f8c.png)
?

**Comment by jwflory** [comment]
@Idadelveloper Yes! 👍🏻 I just reopened it now and will add it back to our sprint board.
