### ISSUE TITLE
Support a new AsciiDoc admonition block: IMPORTANT

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#64]
# Summary

When an AsciiDoc `IMPORTANT` admonition is used, it should be more distinguished from the rest of the content on a page.

# Background

**Is the new feature related to a problem? Describe the problem**: AsciiDoc supports several kinds of [admonitions](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#admonitions), but when they are used, they are not visually distinguished:

![Screenshot of an AsciiDoc admonition when used in the Inventory theme](https://user-images.githubusercontent.com/4721034/157732830-b326108f-bfce-4676-a898-2b8f02ca6173.png "Screenshot of an AsciiDoc admonition when used in the Inventory theme")

**What does the new feature look like to you?**: Each admonition should use a unique icon and color to visually represent the admonition. It should be visually distinguished from the rest of the content on a page.

# Details

There are many AsciiDoc admonitions, and a `IMPORTANT` is just one type. For icons, we should take an approach like using a common set of open source icons that can be used for all admonitions. This way, they will also be more similarly matched to each other. Additionally, when each admonition is used, AsciiDoc+Hugo will automatically create HTML `id` and `class` attributes so they can be styled further with layouts and CSS. To see these attributes, you will need to edit a content page, add the admonition, run the Hugo server, and use the browser tools to inspect the element on the rendered page to see what the HTML attributes are.

For the `IMPORTANT` admonition, this could be a red color with an icon to catch attention or symbolize something urgent. It should catch the reader's attention—it is something important!

![Screenshot of an example IMPORTANT admonition from another site.](https://user-images.githubusercontent.com/4721034/157734373-dd7c3fec-9ec6-425b-86ae-29d101b87457.png "Screenshot of an example IMPORTANT admonition from another site.")

# Outcome

`IMPORTANT` admonitions are supported with a unique appearance in the rendered site when used in content files.

**Comment by Yavnikaa** [comment]
May I work on this? I'll craft an icon set which can be used consistently for all the admonitions.

**Comment by jwflory** [comment]
@Yavnikaa Sure, you can start working on this one 👍🏻 Curious to know what icon set you go with. We should use an open source set where possible.

**Comment by Yavnikaa** [comment]
I followed the steps indicated above and came up with a design for the admonition block. I prepared these two iterations:

![image](https://user-images.githubusercontent.com/56485761/159065892-7360189b-8e5b-4e1c-9014-9dd70ddf1fd1.png)

![image](https://user-images.githubusercontent.com/56485761/159065939-c85e1b36-972c-4d85-ac5f-7ec2a24d37bc.png)

I found the second-one more attention seeking and hence a better fir for the purpose.
Since, the icons on homepage of the inventory website are line icons, I setlled on [Feather Icons](https://feathericons.com/) to pickup the icons from. It is open-source and we can credit the creator too.

I came up with a sample set.

![image](https://user-images.githubusercontent.com/56485761/159066272-0b725521-2252-456f-a119-de52c7195f35.png)

Looking forward to the feedback! If you like these, I can create my PR for the IMPORTANT label and others can follow it easily, to complete the tasks asap. :))

**Comment by jwflory** [comment]
@Yavnikaa Thanks for the mockups. I agree the second one has better contrast. Your sample set is a great model for what this should look like. 👍🏻

Feather Icons look nice too! When adding them, let's make a note in the _Legal_ section of the README. It can go in a new list titled _Attributions_ with name and URL.

Go ahead with the implementation, looking forward to seeing your Pull Request! Have a good weekend.

**Comment by Yavnikaa** [comment]
![Screenshot (219)](https://user-images.githubusercontent.com/56485761/159078879-a694e5ff-9934-41fd-aded-fb56bd3330d7.png)

Just a little confirmation here. Since the blocks currently follow a table structure, changing only the CSS won't do to match our design. Can I alter the html structure as well in the layouts section ?

**Comment by Neha9849** [comment]
@jwflory @Yavnikaa As we already have shortcodes for the note, tip, info and warning admonitions in our theme as `notice`. I think they look great and will also give impact on the user.
Here is a Screenshot of what i am talking about-

![image](https://user-images.githubusercontent.com/85057583/159642008-55c2eb56-d11d-48e2-8a4c-49fae8b1ead5.png)
We can either go with this styling and add the additoinal admonitions like caution or go with the styling in PR #75.

@jwflory with which one should we go ahead?

**Comment by jwflory** [comment]
@Neha9849 Yeah, this was the key question! I was naïve to open the issues. It happens though! As I explained in [my note in #63](https://github.com/unicef/inventory-hugo-theme/issues/63#issuecomment-1082635183), I think we should stick to using the shortcodes.

@Yavnikaa Could we pass this issue to @BeeBombshell to work on while you tackle #35? I think this will help keep everyone working on something impactful.

**Comment by Yavnikaa** [comment]
Yes sure. No issues! :))

**Comment by jwflory** [comment]
Thanks, @Yavnikaa!

@BeeBombshell, shall I assign you for #64 and #66?

**Comment by BeeBombshell** [comment]
Sure @jwflory! I'll start working on them right away! 😄

**Comment by BeeBombshell** [comment]
@jwflory I've added the shortcodes for both the `IMPORTANT` and `CAUTION` admonitions and changed the stylesheet to match the existing designs. The outcome is as follows:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/53828745/160775632-cddda3d7-d865-4458-84ce-b4f90219233d.png">

**Comment by jwflory** [comment]
@BeeBombshell Amazing 💯 I'll review #83 by end of today U.S. Eastern time.
